{
 "title": "Crescent Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Pool value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "crescent_pool_value", "legendFormat": "Pool {{pool_id}}" }
   ]
  },
  {
   "title": "Pool price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "crescent_pool_price", "legendFormat": "Pool {{pool_id}}" }
   ]
  },
  {
   "title": "Last price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "crescent_last_price", "legendFormat": "Pair {{pair_id}}" }
   ]
  },
  {
   "title": "# Orders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "crescent_num_orders", "legendFormat": "Pair {{pair_id}}" }
   ]
  },
  {
   "title": "# Deposit requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "crescent_num_deposit_requests", "legendFormat": "Pool {{pool_id}}" }
   ]
  },
  {
   "title": "# Withdraw requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "crescent_num_withdraw_requests", "legendFormat": "Pool {{pool_id}}" }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "crescent_price", "legendFormat": "{{denom}}" }
   ]
  },
  {
   "title": "Mint rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "crescent_mint_rate", "legendFormat": "Mint rate" }
   ]
  },
  {
   "title": "bToken supply",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "crescent_btoken_supply", "legendFormat": "bToken supply" }
   ]
  }
 ]
}